const STORE = {
    poses: [
        {
            id: 1,
            nameEng: 'Fierce Pose',
            alias: 'Chair',
            nameSan: 'Utkatasana',
            benefits: 'Improves balance, mobility, posture, strengthens legs, glutes and ankles, opens chest and shoulders',
            img: '',
            utube: "https://www.youtube.com/embed/Kp7XJkG9ubc",
            level: 'begginer',
            poseType: 'balansing, standing pose'
        },
        {
            id: 2,
            nameEng: 'Half Lord of the Fishes Pose',
            alias: 'Sitting Half Spinal Twist',
            nameSan: '',
            benefits: 'Strengthens and lengthens the spine, cleanses internal organs, activates digestive tract, opens the chest and heart space',
            img: 'https://www.dropbox.com/s/u9joi8lbntxumyh/seatedspinaltwist.svg?raw=1',
            utube: 'https://www.youtube.com/embed/OMGUMuUbK4Q',
            level: 'intermiate',
            poseType: 'seated, twist',
        },
        {
            id: 4,
            nameEng: 'Revolving Side Angle Pose',
            alias: '',
            nameSan: 'Parivrtta Parsvakonasana',
            benefits: 'Improves flexibility, strengthens legs and core, opens the hips, chest, and shoulders, massages internal organs, improves digestion',
            img: '',
            utube: 'https://www.youtube.com/embed/XRfxkioaG-Q',
            level: 'intermidate',
            poseType: 'balansing, twist, standing',
        },
        {
            id: 5,
            nameEng: 'Side Angle Pose',
            alias: '',
            nameSan: 'Parsvakonasana',
            benefits: 'Stretches the inner thighs, groins, and side body, Strengthens the quadriceps and hamstrings, as well as the hips, knees, and ankles, Improves stamina, Relieves low back pain, menstrual pain, and sciatica, Massages the abdominal organs, Opens the chest and shoulders',
            img: '',
            utube: 'https://www.youtube.com/embed/7fFWy2IT9FE',
            level: 'begginer',
            poseType: 'balansing, standing',
        },
        {
            id: 6,
            nameEng: 'Reverse Tabletop Pose',
            alias: '',
            nameSan: 'Ardha Purvottanasana',
            benefits: 'Opens the heart space, opens the frontline of body, engages the core and quadriceps',
            img: '',
            utube: 'https://www.youtube.com/embed/nWaOi23tXeA',
            level: 'begginer',
            poseType: 'strengthening, seated, backbend',
        },
        {
            id: 7,
            nameEng: 'Tabletop Pose',
            alias: '',
            nameSan: 'Bharmanasana',
            benefits: 'Strengthens arms, shoulders, and knees, offers space to open your spine, grounds your energy and calms your nervous system',
            img: '',
            utube: 'https://www.youtube.com/embed/MeNKrcLDexA',
            level: 'begginer',
            poseType: 'seated',
        },
        {
            id: 8,
            nameEng: 'Tree pose',
            alias: '',
            nameSan: 'Vrksasana',
            benefits: 'Tones leg muscles, engages core muscles, enhances balancing abilities, aids in the alignment of the spine, lessens stress by improving focus and alertness',
            img: '',
            utube: 'https://www.youtube.com/embed/wdln9qWYloU',
            level: 'begginer',
            poseType: 'standing, balancing',
        },
        {
            id: 9,
            nameEng: 'Warrior 3',
            alias: '',
            nameSan: 'Virabhadrasana III',
            benefits: 'Strengthens the entire body, improves balance, improves posture, aids in increasing energy and boosting concentration',
            img: '',
            utube: 'https://www.youtube.com/embed/S74efRiLo6k',
            level: 'intermediate',
            poseType: 'standing, balancing',
        },
        {
            id: 10,
            nameEng: 'Warrior 2',
            alias: '',
            nameSan: 'Virabhadrasana II',
            benefits: 'Strengthens the entire body, improves mobility in hips',
            image: '',
            utube: 'https://www.youtube.com/embed/PZcp3Lz7WJs',
            level: 'begginer',
            poseType: 'standing, balancing',
        },
        {
            id: 11,
            nameEng: 'Warrior 1',
            alias: '',
            nameSan: 'Virabhadrasana I',
            benefits: 'Strengthens the entire body, improves mobility in hips, stretches back foot, chest',
            image: '',
            utube: 'https://www.youtube.com/embed/4hqmLOpkHrw',
            level: 'begginer',
            poseType: 'standing, balancing',
        },
        {
            id: 12,
            nameEng: 'Rested Half Pigeon Pose',
            alias: 'Pigeon',
            nameSan: 'Ardha Kapotasana',
            benefits: 'Cleanses the liver, restorative energy, opens the hips deeply, releases stored emotions',
            image: 'https://www.dropbox.com/s/77peru289zm446u/pigeon.svg?raw=1',
            utube: 'https://www.youtube.com/embed/jkJwvzt12dA',
            level: 'intermidiate',
            poseType: 'forward fold, Hip Opener, Seated',
        },
        {
            id: 13,
            nameEng: 'Cobra',
            alias: '',
            nameSan: 'Bhujangasana',
            benefits: 'Improves spinal flexibility and mobility, deepens breathing, strengthens shoulders and chest, opens heart space, energizes entire body, Lessens stress ',
            image: '',
            utube: 'https://www.youtube.com/embed/ZqnbaBx09-E',
            level: 'begginer',
            poseType: 'backbend, heart opener',
        },
        {
            id: 14,
            nameEng: "Bharadvaja's Twist",
            alias: '',
            nameSan: 'Bharadvajasana',
            benefits: 'Massages the abdominal organs Improves digestion Stretches the spine and shoulders Increases spinal flexibility Relieves stress',
            image: '',
            utube: 'https://www.youtube.com/embed/Z43c1aeAMeM',
            level: 'intermidiate',
            poseType: 'Hip Opener,  Seated, Twist',
        },
        {
            id: 15,
            nameEng: 'Boat',
            alias: '',
            nameSan: 'Paripurna Navasana',
            benefits: 'Strengthens the hips flexors, abdominals, and low spine, Focuses the mind, Improves overall core strength, Strengthens the quadriceps, Improves coordination and balance, Stimulates the abdominal organs and improves digestion, Stimulates the kidneys, thyroid, and prostate glands',
            image: '',
            utube: 'https://www.youtube.com/embed/UHSqdPl2R4Q',
            level: 'begginer',
            poseType: 'Balance, Seated, Strenghening',
        },
        {
            id: 16,
            nameEng: 'Bound Angle Pose',
            alias: '',
            nameSan: 'Baddha Konasana',
            benefits: 'Lengthens and releases adductor muscles of the groin, Stretches the low back and thighs, Improves external rotation of the hips, Strengthens the hip flexors and abdominals, Stimulates the abdominal organs and digestive system, Relieves symptoms of menstruation and menopause',
            image: '',
            utube: 'https://www.youtube.com/embed/RWvNyJyasiI',
            level: 'begginer',
            poseType: 'Forward Fold, Hip Opener, Seated',
        },
        {
            id: 17,
            nameEng: 'Bow pose',
            alias: '',
            nameSan: 'Dhanurasana',
            benefits: 'Lengthens the hip flexors and strengthens the hamstrings, Detoxes the kidneys and adrenal glands, Strengthens the shoulders and spine extensors, Opens the chest and throat',
            image: '',
            utube: 'https://www.youtube.com/embed/4P2mYcOGxbU',
            level: 'intermediate',
            poseType: 'Backbend, Heart Opener',
        },
        {
            id: 18,
            nameEng: 'Bridge pose',
            alias: '',
            nameSan: 'Setu Bandha Sarvangasana',
            benefits: 'Stimulates the thyroid, Improves posture and opens rounded shoulders, Stretches the abdominal organs and improves digestion, Tones the female reproductive organs, Relieves anxiety, fatigue, and insomnia',
            image: '',
            utube: 'https://www.youtube.com/embed/JY9TLhKIQdE',
            level: 'begginer',
            poseType: 'Backbend, Heart Opener',
        },
        {
            id: 19,
            nameEng: 'Camel pose',
            alias: '',
            nameSan: 'Ustrasana',
            benefits: 'Stretches the vertebrae, Massages the abdominal organs and stimulates digestion, Stretches the neck, chest, abs, hips, and thighs, Stimulates the spinal nerves, Strengthens the back muscles and core, Improves posture, Regulates the thyroid',
            image: '',
            utube: 'https://www.youtube.com/embed/8q7GxnIFsQo',
            level: 'intermediate',
            poseType: 'Backbend, Heart Opener',
        },
        {
            id: 20,
            nameEng: 'Cat',
            alias: '',
            nameSan: 'Marjaryasana',
            benefits: 'Strengthens the arms, wrists, and shoulders, Relieves tension in the thoracic, cervical, and lumbar spine; warming up the back for practice, Gently massages the abdominal organs and improves digestion, Strengthens and tones the abdominal muscles, Increases spinal flexibility',
            image: '',
            utube: 'https://www.youtube.com/embed/Ov65nNSWrfw',
            level: 'begginer',
            poseType: 'Backbend, Core',
        },

    ]

}



export default STORE ;